### ISSUE TITLE
M.Tech thesis report

### ISSUE THREAD

**Issue by piyush-kurur** [TypeDB/bloc#3]
@igniting Do you have the soft copy of the M.Tech thesis that you submitted based on this project ?
If you do have it, can you send it to me? There is some B.Tech student here who wants to
continue on the stuff that you did.

**Comment by igniting** [comment]
https://github.com/igniting/masters-thesis/blob/gh-pages/static/thesis.pdf

**Comment by piyush-kurur** [comment]
Thanks.
